git_branch: develop

# DNS configurations
domain: localhost

# django config
debug_mode: True

secret_key: sdlgbdfkjgb94ibrego493gtbhr3iuvfwg944tre
allowed_hosts: 127.0.0.1

default_superuser_email: admin@admin.com
default_superuser_password: 1qaz2wsx3

# Database configurations
db_user_password: 12345678
db_host: '127.0.0.1'

raven_dsn:

# Console customization
console_promt: PS1="\[\033[01;32m\]\u@development \[\033[01;34m\]\t \w \$ \[\033[00m\]"

https: False  # If server configuration is https
ssl_certificate_path:
ssl_certificate_key_path:

# cors settings
cors_disabled: True
cors_allowed_hosts: 127.0.0.1, localhost

web_client_backend_url: http://localhost:8000